### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by developer-lindner** [sghall/react-compound-slider#10]
see topic, would be nice to have it.

**Comment by sghall** [comment]
Yep.  Going to get back into project shortly.  I'd like to add typings.  Any interest in doing a PR on this?

**Comment by sghall** [comment]
Released in 0.14.0

Typescript example on CodeSandbox https://codesandbox.io/s/6zpjmw1x3w

**Comment by diffractometer** [comment]
@sghall 👍  thanks for sharing.
