### ISSUE TITLE
TracksProps interface not included in package exports

### ISSUE THREAD

**Issue by m7kvqbe1** [sghall/react-compound-slider#100]
### Problem or feature description:

The TracksProps TypeScript interface has not been included in the package exports:

https://github.com/sghall/react-compound-slider/blob/40552d3a6eda448277c4531b88d460c75ecbd1b4/src/index.d.ts#L16

### Steps to reproduce (for problems):

Attempt to import interface from package:

```
import { TracksProps } from 'react-compound-slider'

// doesn't exist
```

### Versions (for problems):

React-Compound-Slider: `^2.3.0`

React: -

Browser: - 

Operating System: -

**Comment by sghall** [comment]
Thanks!  Released in version `2.4.0`
