### ISSUE TITLE
Documentation for String Values

### ISSUE THREAD

**Issue by VLegatus** [sghall/react-compound-slider#103]
New to this, sorry if it's bad form.
### Problem or feature description:
I will probably forget how to turn the ticks into a string. I already did it, but I would love to contribute to documentation on it. If wanted, where would be the best place to put it? Under ticks?

Also relevant sandbox pops an error and doesn't display: https://codesandbox.io/s/y08pv1ok7j

**Comment by sghall** [comment]
I think the dependencies were just out of date https://codesandbox.io/s/y08pv1ok7j
