### ISSUE TITLE
Feature Request: Expose optional handle ID for onUpdate

### ISSUE THREAD

**Issue by bpote** [sghall/react-compound-slider#11]
### Problem or feature description:

First of all, thank you for great slider. It works great and is very flexible unlike some of the other react sliders I've tried.

It would be great to know what handle is being dragged. I briefly looked at the tutorial and documentation but could not find it so apology if this already exists. I am passing custom handle IDs and would like to map the dragged handles values based on those IDs.

My use case is I have multiple (> 2) handles that can cross each other and need to track which value is for which parameter. Position would not be enough for me to map the values back to the right attributes. Any alternative thoughts with react-compound-slider that exposing handle ID would be appreciated too.

**Comment by bpote** [comment]
@sghall thanks! yes, being able to pass values in that format would work perfectly for the use case I've. Is that the current ability you are describing above or is it something you've in mind? When I try the format above, I get warning which seems as expected as seen in https://github.com/sghall/react-compound-slider/blob/ada05aa24dc8ad4f3f31d4e4f209818bfe527f11/src/Slider/Slider.js#L92-L102

**Comment by sghall** [comment]
No.  That's not the current functionality.  I think that is doable though.  I'll take a look at this shortly.

**Comment by sghall** [comment]
Just did a big re-write of the slider.  Unfortunately,  after looking at it,  I don't think I can support this feature right now and keep things stable.  Be glad to look at a PR on this.
