### ISSUE TITLE
Slider not working properly on firefox

### ISSUE THREAD

**Issue by Mitali-C** [sghall/react-compound-slider#116]
### Problem or feature description:
I tried to create a range slider using 'react-compound-slider'. It works fine on chrome but is not working on firefox.

This is how it looks on chrome:
![image](https://user-images.githubusercontent.com/40625283/83040314-c02f9280-a05c-11ea-92b8-f8c3647c15f7.png)

And on firefox:
![image](https://user-images.githubusercontent.com/40625283/83040394-d50c2600-a05c-11ea-9659-28f37cc7796d.png)

Browser: Firefox (current)

**Comment by RanSolo** [comment]
You've got something going on.  It recently developed a time range slider component primarily using Firefox and it worked without any issues.

**Comment by sghall** [comment]
I just tried loading some of the sandboxes in FireFox and the demo site and I don't see any issues.  If you can produce a demo, I'd take a look.  Probably just don't have any width defined in Firefox.
