### ISSUE TITLE
Max Range

### ISSUE THREAD

**Issue by plaeski** [sghall/react-compound-slider#12]
Is adding a max selected range on the road map?

I currently have a use case where I need to cap the selected range to x number of ticks. For example, having a range of 12 hours on the slider and having a max selection of 6 of those hours.

Thanks for making this great library! It's been a pleasure to work with :smile:

**Comment by sghall** [comment]
Hi there.  Yeah, this sounds pretty useful.  I think that's going to be a "custom mode."  Basically you'll pass in a function and you can define custom functionality as the slider moves. I'll report back here when that's working and you can try it out.

**Comment by sghall** [comment]
Alrighty.  This one is in there.  You can now create a custom mode by passing a function to the mode prop.

Example at the bottom here:
https://sghall.github.io/react-compound-slider/#/slider-demos/material-ui

**Comment by manahga** [comment]
Great addition.  Really adds to the customization.  Kudos!

**Comment by koenoe** [comment]
@sghall is the demo you linked to last year still available somewhere?

**Comment by sghall** [comment]
It got taken down.  Here's the relevant code:

```js
        <Slider
          mode={(curr, next) => {  // for a range slider (two handles) with max separation of 100
            const [{ val: val1 }, { val: val2 }] = next
            if (Math.abs(val1 - val2) > 100) {
              return curr
            }

            return next
          }}
          step={5}
          domain={domain}
          className={classes.slider}
          onUpdate={this.onUpdate}
          onChange={this.onChange}
          values={values}
        >
           ...
        </Slider>
```

**Comment by koenoe** [comment]
Cheers mate, thank you
