### ISSUE TITLE
Showing rail in varying color based on tick position

### ISSUE THREAD

**Issue by vaibhav-kona** [sghall/react-compound-slider#121]
### Problem or feature description:
Is it possible to show different colors on the rail based on the tick position like in the pic?

### Steps to reproduce (for problems):

![Screen Shot 2020-07-20 at 10 20 33 PM](https://user-images.githubusercontent.com/5622964/87964329-aef08880-cad7-11ea-9f92-a0fa1296948f.png)

### Versions (for problems):

React-Compound-Slider: 2.5.0

React: 16.12.0

Browser: Firefox Browser 79

Operating System: Mac OS 10.15.5

**Comment by sghall** [comment]
Hey there,  that just looks like a gradient on the rail with no tracks showing...

Would this work?
https://codesandbox.io/s/react-compound-slider-mum9k?file=/components.js

<img width="428" alt="Screen Shot 2020-07-20 at 4 48 14 PM" src="https://user-images.githubusercontent.com/4615775/87997079-f7448200-caa8-11ea-9a67-7a894dbefe73.png">

CSS gradients:
https://www.w3schools.com/css/css3_gradients.asp

**Comment by vaibhav-kona** [comment]
Yes, the gradients are getting distributed evenly. So, this works. Thanks!
