### ISSUE TITLE
the name of Ticks is undefined

### ISSUE THREAD

**Issue by chenzhutian** [sghall/react-compound-slider#129]
### Problem or feature description:
Since Ticks is an anonymous function, its name is undefined.
Thus, isRCSComponent will return true if pass in a dom. 

### Steps to reproduce (for problems):

just put a <div> into slider
```
<Slider>
        <div>

        </div>
</Slider>
```

![image](https://user-images.githubusercontent.com/3315274/99114551-d2b76d00-25a5-11eb-9a22-5e32915ac807.png)

**Comment by sghall** [comment]
Thanks for reporting this!  That should be fixed now in version 3.3.0 so try it out and let me know if there's any issues.

**Comment by chenzhutian** [comment]
awesome!
