### ISSUE TITLE
Updating steps dynamically

### ISSUE THREAD

**Issue by vertic4l** [sghall/react-compound-slider#13]
Is there a safe proper way to update steps on behalf?

Like:
step=0.1 if onUpdate value < 1
step=0.5 if onUpdate value < 2
step=1 if onUpdate value > 2

Tried to modify state of step onUpdate and pass it as step prop, but that doesn't seems to work well.

Any ideas?

**Comment by sghall** [comment]
Hey there.  Just took care of a bunch of maintenance stuff and going to try to clear these issues over the next week.  I think this is manageable, but need to make some tweaks. 

So I think the values will have to be checked and, potentially, recoded to the nearest valid value given the updated step in this scenario. If the step goes from 0.1 to 0.5 and there's a value at 10.4 it would move to 10.5 for example. You can either let the slider do this on its own or you can send an updated set of values recoded how you like when you change the step.  

Does this sound about right?  Just want to make sure I understand the issue.

**Comment by sghall** [comment]
Try this out now.  I believe this should be working with this fix https://github.com/sghall/react-compound-slider/issues/14

**Comment by sghall** [comment]
Ok.  Kinda depends on exactly what the logic is.  If you can create a sandbox that reproduces it, I'll take a look.

Probably could just fork one of these:
* [Basic Multi-Slider on CodeSandbox](https://codesandbox.io/s/plzyr7lmj)
* [Date/Time Slider on CodeSandbox](https://codesandbox.io/s/rw97j317p)
* [Video Slider on CodeSandbox](https://codesandbox.io/s/1z51zn6q23)
* [Slider w/ Tooltips (Typescript)](https://codesandbox.io/s/pjwwzzj8qm)
* [SVG Slider on CodeSandbox](https://codesandbox.io/s/qk0vovqw6)
* [Value Slider on CodeSandbox (Typescript)](https://codesandbox.io/s/6zpjmw1x3w)
* [Range Slider on CodeSandbox (Typescript)](https://codesandbox.io/s/zl8nrlp9x)
* [Custom Feet-Inches Ticks on CodeSandbox (Typescript)](https://codesandbox.io/s/5262w7r9yx)
* [Custom Feet-Inches Ticks - Vertical on CodeSandbox (Typescript)](https://codesandbox.io/s/18lkz04y8j)
