### ISSUE TITLE
Change in step behavior

### ISSUE THREAD

**Issue by damusnet** [sghall/react-compound-slider#130]
### Problem or feature description:

After upgrading from 2.5.0 to 3.3.0, the `step` seems to behave differently

### Steps to reproduce (for problems):

See: https://codesandbox.io/s/react-compound-slider-forked-dsxwl?file=/index.js

* I forked [the first CodeSandbox example](https://codesandbox.io/s/plzyr7lmj),
* changed `domain` to `[0, 100]`
* changed `defaultValues` to `[0, 100]`
* changed `step` from `1` to `0.1`

Instead of the Track taking 100% of the width, it now takes 1%.

![image](https://user-images.githubusercontent.com/433409/99301030-99336b80-280a-11eb-9c85-3e1ea27ca104.png)

### Versions (for problems):

React-Compound-Slider: 3.3.0

React: 16.14.0

Browser: Chrome 86.0.4240.193 (Official Build) (x86_64)

Operating System: macOS Catalina 10.15.7 (19H15)

**Comment by sghall** [comment]
Thanks for reporting this!  Extra special thanks for the sandbox 😉   Yep, see what you mean.  That is curious.  I'll take a look.

**Comment by damusnet** [comment]
Caught it in our snapshot tests as I was upgrading the library this morning. Thanks for looking into it and thanks for an otherwise great library!

**Comment by sghall** [comment]
Yes, this was a nice catch for sure.  I put out a fix for this in version 3.3.1 so give it a shot.  I tried it out in that sandbox but please let me know if you see any other issues.    Appreciate the help on this.  I'm trying to gradually move the the code towards a bigger refactor and have bumped some stuff out of place in the process.

**Comment by damusnet** [comment]
All tests passed on our end and the updated lib is being merged as I type!

Thank you very much for such a quick fix! Really appreciate your work!
