### ISSUE TITLE
Handle tooltips need number formatting

### ISSUE THREAD

**Issue by kpounds81** [sghall/react-compound-slider#134]
### Problem or feature description: 
When working with larger slider number (in U.S. numbers over 999 are easier to read with a comma i.e. 1,000). Currently I don't see support for this. Could there be a new feature that uses JS [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) and allows the user to pass in their locale to apply number formatting? Would be really useful I'm sure for others as well.

### Steps to reproduce (for problems): 
Create a domain or use values that are large number like 5,000 or something similar.

### Versions (for problems): 
current

React-Compound-Slider: v 3.3.1

React: v 16.12.0

Browser: Chrome

Operating System: Windows

**Comment by sghall** [comment]
Hey there.  This library doesn't have anything to do with the formatting of the values in the tooltips (there are some demos with tooltips to show you how to do it).   In JS you can just call   `myNumber.toLocaleString()` to get a formatted string.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

So in the tooltip demos you could just use that here:
https://github.com/sghall/react-compound-slider/blob/b24286d953df08b0ffe508ed5b8bc5741b6068da/docs/src/demos/tooltips/components.tsx#L81
