### ISSUE TITLE
Feature Request: Provide update/change event when automatically rounding intial value to nearest step

### ISSUE THREAD

**Issue by manahga** [sghall/react-compound-slider#14]
First off, love the slider!  Excellent work...

I noticed during some testing that when providing an initial value to the slider that is outside of the step boundaries, the slider will automatically round the value to the nearest valid step.  This is fine!  However, there is no update or change event raised for this change.  For users that are using a state management system, the lack of an update/change event prevents us from properly updating the state for the slider.  

Would love it we could receive the proper events for this initial change.

Steps to reproduce:

- Build your slider
- Set the step for your slider to 10
- Set the initial value to 35
- Set your callback for the onChange/onUpdate event
- Add a breakpoint within the callback
- Test it.  The value for the slider will automatically be changed to 40 and no events will be raised

This was tested on both Chrome and Firefox browsers.

**Comment by sghall** [comment]
Yep.  That makes sense.  I think I'm going to call BOTH onChange and onUpdate in this scenario. Right?

I'm doing a pretty substantial re-write this week so I'll get this in there. Should be out shortly.

**Comment by sghall** [comment]
Released in 0.11.0.  Try it out and let me know if there's any issues.

**Comment by manahga** [comment]
Works like a charm! Thank you!
