### ISSUE TITLE
Dynamical setup of slider component

### ISSUE THREAD

**Issue by NikitaSpirit** [sghall/react-compound-slider#15]
Hello!
I have one issue. When I'm trying to pass props to my child component to dynamically setup such properties of Slider as domain or values I get error "value.toFixed is not a function". So it looks like Slider only works with static property values.
Is it possible to use react-compound-slider with props passed as property values?

**Comment by sghall** [comment]
I think you're just sending non-numeric values for the domain.  Domain should be like [0, 100].  Should update the props validation to catch that.

**Comment by sghall** [comment]
Only place in the code is here...
https://github.com/sghall/react-compound-slider/blob/f6356dd2b3c0e922ae713667095ecba9ccc8b12b/src/Slider/utils.js#L54

**Comment by sghall** [comment]
Hopefully, that addressed the issue.  Open this back up if there's other issues.

**Comment by NikitaSpirit** [comment]
@sghall  You are right! I passed string instead of number as parameters. It's only because because of my inattention. Thank you Steve!

**Comment by omarshiha** [comment]
what if i want to use an array of strings to display instead of min, max ints like this => "[min, max]"
