### ISSUE TITLE
Disable handles dynamically

### ISSUE THREAD

**Issue by vertic4l** [sghall/react-compound-slider#16]
### Problem or feature description:

There are cases where you would like to disable handles dynamically.
Couldn't find anything related to it in source code. Could that be added ?

**Comment by sghall** [comment]
Hey there.  Hmmmm...what do you mean exactly?  You provide the Handle component so you can actually do that right now.  Maybe I don't understand correctly. 

If you look here:

https://github.com/sghall/react-compound-slider/blob/master/docs/src/pages/slider-demos/horizontal/components.js#L33

Get handle props returns onMouseDown and onTouchStart handlers so you can disable dragging yourself.  Just pass in a disabled prop to your Handle component and only call the handlers if it's not disabled.

https://github.com/sghall/react-compound-slider/blob/master/src/Handles/Handles.js#L11

Does that make sense?

**Comment by xinsight** [comment]
To anyone else who wants to disable input. You have to send an empty callback to Handle instead of the default getHandleProps.
```
 <Handles>
  {({ handles, getHandleProps }) => (
    <div className={'slider-handles' + (disabled ? ' disabled' : '')}>
      {handles.map(handle => (
        (<Handle
          key={handle.id}
          handle={handle}
          getHandleProps={disabled ? () => {} : getHandleProps}
        />)
      ))}
    </div>
  )}
</Handles>
```
(I'm also adding a 'disabled' class to the container so that I can style the disabled handle appearance.)

**Comment by xinsight** [comment]
And a followup - if you want to disable setting the value by clicking on the track, you need to wipe Rail's `onMounseDown` and `onTouchStart` handlers. (`disabled` comes from my parent component that creates the `Slider`.

```
  <Slider>
        <Rail>
          {({getRailProps}) => {
            let props = getRailProps()
            if (disabled) {
              props.onMouseDown = () => {}
              props.onTouchStart = () => {}
            }
            return <div className="slider-rail" {...props} />
          }}
        </Rail>
  </Slider>
```

@sghall: Disabling a component is a common use case. Could

**Comment by xinsight** [comment]
`<Tracks>` also has touch handlers, so you need to wipe the handlers there as well to disable.

```jsx
        <Tracks left={true} right={false} {...tracksProps}>
          {({ tracks, getTrackProps }) => {
            let props = getTrackProps()
            if (disabled) {
              props.onMouseDown = () => {}
              props.onTouchStart = () => {}
            }
            return <div className="slider-tracks">
              {tracks.map(({ id, source, target }) => (
                  <div key={id} className="slider-track"
                    style={{left: `${source.percent}%`, width: `${target.percent - source.percent}%`}}
                    {...props}
                  />
              ))}
            </div>
          }}
        </Tracks>
```

**Comment by sghall** [comment]
Hey @xinsight maybe you're right.  I guess I was thinking DYI disabling was the way to go.  I'm trying to think what it would do exactly.  I think you're saying setting the disabled prop to true would unhook the listeners and it would also be passed as a prop?

Looks like killing the listeners would be pretty simple here...
https://github.com/sghall/react-compound-slider/blob/623546306a1ffaead034af0312769cb413d381ff/src/Slider/Slider.js#L442

Then you'd have to pass it down as a prop like in Tracks.
https://github.com/sghall/react-compound-slider/blob/623546306a1ffaead034af0312769cb413d381ff/src/Tracks/Tracks.js#L11

You interested in doing PR on this?  Anyone else have any strong opinions on this?

**Comment by xinsight** [comment]
Yeah, I was thinking of a slider disabled prop would cause empty callbacks to be passed down to the lower components. i.e. `getRailProps()` and `getTrackProps()` would just return empty callbacks.

i'll look into this - and will make a PR if I figure out how to do it cleanly.

**Comment by sghall** [comment]
Right. Yeah, maybe just add  a `const noop = () => {}` at the top of the file in Slider and pass that when disabled === true.  

Ok. Awesome.  I'll look for the PR.

**Comment by Absvep** [comment]
Hi,
Is it possible to change Tracks className based on disabled prop? I want to change to Tracks color when the Slider is disabled. The below does not work as it seems that disabled prop is not passed down:

```
function Track({
  disabled,
  source,
  target,
  getTrackProps,
}) {
  // your own track component
  return (
    <div
      className={`${
        disabled ? 'bg-red-400' : 'bg-blue-400'
      } absolute sliderHeight tracksMt bg-blue-400 cursor-pointer`}
      style={{
        left: `${source.percent}%`,
        width: `${target.percent - source.percent}%`,
      }}
      {...getTrackProps()}
    />
  );
}
```

**Comment by PriyaJainDev** [comment]
Is there any possibility of disabling only one of the handlers of the range slider while keeping another handler movable?
