### ISSUE TITLE
Demo page can't be used with wide windows

### ISSUE THREAD

**Issue by kichik** [sghall/react-compound-slider#2]
When the page is wide enough, the navigation bar stays open forever. But when the navigation bar is open, the content of the page is disabled. It can't be scrolled and it can't be interacted with. I had to reduce the window size to be able to play with the examples.

**Comment by sghall** [comment]
Hey, thanks.  I really appreciate you taking the time to let me know.  I pushed a fix up there.  Seems to solve the issue for the moment.  Need to look at it tomorrow.
