### ISSUE TITLE
Component Documentation Incorrect

### ISSUE THREAD

**Issue by neilchaudhuri** [sghall/react-compound-slider#22]
### Problem or feature description:

I am currently attempting to use RCS (with TypeScript) to build a height slider (for people) where the tracks represent half-inch increments and the labels represent "landmarks" like "5 ft." or "5 ft. 6" or "6 ft." The problem is I keep finding the documentation to be outdated on major components. Thankfully I found [this example](https://codesandbox.io/s/6zpjmw1x3w) by @sghall, but it's missing the `Ticks` component. I figured that out, but now I am having issues with `Handle` and `Tick`.

Can this example be supplemented with more components so I (and imagine others) can have something to work from?

Thanks.

FWIW here is the component:

```
<Slider
                mode={1}
                step={1}
                domain={}
                rootStyle={sliderStyle}
                onChange={this.onChange}
                values={values}
            >
                <Rail>
                    {({ getRailProps }) => (
                        <div style={railStyle} {...getRailProps()} />
                    )}
                </Rail>
                <Handles>
                    {({ handles, getHandleProps }) => (
                        <div className="slider-handles">
                            {handles.map(handle => (
                                
                                <Handle
                                    key={handle.id}
                                    handle={handle}
                                    domain={handle.id}
                                    getHandleProps={getHandleProps}
                                />
                            ))}
                        </div>
                    )}
                </Handles>
                <Tracks right={false}>
                    {({ tracks, getTrackProps }) => (
                        <div className="slider-tracks">
                            {tracks.map(({ id, source, target }) => (
                                <Track
                                    key={id}
                                    source={source}
                                    target={target}
                                    getTrackProps={getTrackProps}
                                />
                            ))}
                        </div>
                    )}
                </Tracks>
                <Ticks count={5}>
                    {({ ticks }) => (
                        <div className="slider-ticks">
                            {ticks.map(tick => (
                                <Tick key={tick.id} tick={tick} count={ticks.length} />
                            ))}
                        </div>
                    )}
                </Ticks>
</Slider>

```
### Versions (for problems): 0.15.0

React-Compound-Slider: 0.15.0

React: 16.4.10 (with TypeScript)

Browser: Chrome Version 69.0.3497.81 (Official Build) (64-bit)

Operating System: macOS High Sierra 10.13.6

**Comment by sghall** [comment]
Really?  Where are the docs not correct?  Could you please point those issues out?  I'd like to get those taken care of.  

I forked the sandbox added some ticks and formatted them like you were talking about. If I understand correctly you want to do something like this...
https://codesandbox.io/s/5262w7r9yx

**Comment by neilchaudhuri** [comment]
Wow this is very helpful and much more than I expected. Thanks. I need to add half-inch increments and a second handle for range purposes, but hopefully I can figure that out myself.

As for the docs, I was finding issues with pieces of almost every samples I tried--particularly in the lower nested components--and those pieces weren't always the same. For example, the [tutorial](https://sghall.github.io/react-compound-slider/#/getting-started/tutorial) gave me an issue with `Ticks` and `Handle`, but then I found another sample that escapes me at the moment where `Ticks` was right. I don't know if it is a TypeScript issue or an outdated API issue.

I know keeping documentation up-to-date is no fun. Maybe I can help once I get more familiar with React and this particular component, but for now I think it makes sense to review all the samples and focus on the deeper nested children.

**Comment by neilchaudhuri** [comment]
By the way, is there something about the styles in your sample that prevent `vertical` from being reflected in the final control? That flag isn't working for me.

**Comment by sghall** [comment]
Great.  I'll go back over the docs with this in mind.  Any other pointers would be welcome.  Yeah, it's always hard to see the docs through a the eyes of someone just approaching a project for the first time.  You're just so into it you can't see it.  That feedback is very valuable.

The vertical would change the styles on the slider and on the inner components (Handle, Track and Tick).  Be like this...
https://codesandbox.io/s/18lkz04y8j

**Comment by neilchaudhuri** [comment]
I got it working. Thanks.
