### ISSUE TITLE
Package module entry should be ESM

### ISSUE THREAD

**Issue by jaydenseric** [sghall/react-compound-slider#24]
At the moment, `index.es.js` in [the published package](https://registry.npmjs.org/react-compound-slider/-/react-compound-slider-0.15.0.tgz) contains ESM. The problem is, all the project files imported from there contain CJS instead of ESM:

<img width="2032" alt="screen shot 2018-09-14 at 8 00 45 pm" src="https://user-images.githubusercontent.com/1754873/45544093-b8fd2c80-b859-11e8-91a2-8b5b8437f782.png">

Ideally the whole project can be imported as ESM, and even better, as `.mjs` files following the Node.js [`--experimental-modules`](https://nodejs.org/api/esm.html#esm_enabling) rules (which Webpack also follows).

Here is an example: https://github.com/jaydenseric/graphql-react/blob/v2.0.0/package.json#L31

**Comment by sghall** [comment]
Appreciate you bringing this to my attention.  Yep, good call.  It was being overwritten with cjs in the build process.  I pushed a fix but haven't released it yet.  

The fix would put an "es" folder inside the package.  The package would end up looking like the attached...
[react-compound-slider.zip](https://github.com/sghall/react-compound-slider/files/2385354/react-compound-slider.zip)

**Comment by sghall** [comment]
Ok.  Released this in 0.15.1 today.  Try it out and let me know if there's any further issues.
