### ISSUE TITLE
Add keyboard navigation

### ISSUE THREAD

**Issue by tbassetto** [sghall/react-compound-slider#26]
### Problem or feature description:
From an accessibility point of view it would be great to let the user use the keyboard to move the handles once they have the focus. It's unclear to me yet if a change needs to happen in `react-compound-slider`. If not, if it can be handled only in the `Handle` component we use, we should make sure that the examples are accessible.

### Steps to reproduce (for problems):
Open https://sghall.github.io/react-compound-slider/#/slider-demos/horizontal and try to use the keyboard to move the handles. It doesn't work.

### Versions (for problems):

React-Compound-Slider: 0.15.1

React: 16.3.2

Browser: Firefox Nightly

Operating System: macOS 10.13.6

**Comment by sghall** [comment]
Yeah, there's no keyboard controls on there.  You mean just support left and right arrow for the handle that's in focus?

**Comment by tbassetto** [comment]
Yes, and I guess up and down if the slider is vertical.

**Comment by sghall** [comment]
Ok.  This was released in version 0.16.0.  Thanks for the help on this!
https://github.com/sghall/react-compound-slider/releases/tag/v0.16.0
