### ISSUE TITLE
Changing Slider domain and value props at the same time creates error in setValues

### ISSUE THREAD

**Issue by CameronAckermanSEL** [sghall/react-compound-slider#29]
### Problem or feature description:
Changing the domain and value props of the slider to a domain that is smaller can cause an "invalid value" warning from the slider.

This is reproducible with the following codesandbox: https://codesandbox.io/s/5woq82rz6k

The root cause appears to be here: https://github.com/sghall/react-compound-slider/blob/master/src/Slider/Slider.js#L82

In this control flow, the conditional on line 68 evaluates to true which causes the range to be updated, and onChange and onUpdate to fire, but the code continues to call `setValues` on line 84 using a stale set of values. This results in the slider ignoring the value prop that is actually being set, and it uses the old value set which is often out of range. The value is then reset to an incorrect value.

### Steps to reproduce (for problems):

1. Mount a slider with a domain and value set.
2. Change the domain and values at the same time to a domain smaller than the original props.
3. Observe that an error is logged to the console stating the range was reset.

### Versions (for problems):

React-Compound-Slider: 0.15.1

React: 16.

Browser: Chrome 

Operating System: Linux

**Comment by CameronAckermanSEL** [comment]
By the way, wanted to say that I tried using rc-slider first and after two weeks of pain I was able to accomplish everything I needed in a single day from this component. It was a real pleasure to use. Thanks for doing such a great job

**Comment by CameronAckermanSEL** [comment]
I have a "fix" for this. I worry the solution is inelegant, but it helped alleviate the problem. 

In Slider.js:
```
  componentWillReceiveProps(next) {
    const { domain, step, reversed, values } = next
    const { props } = this

    if (
      domain[0] !== props.domain[0] ||
      domain[1] !== props.domain[1] ||
      step !== props.step ||
      reversed !== props.reversed
    ) {
      this.updateRange(domain, step, reversed)
      // pass the values in nextProps as an override. In this control flow, when the domain changes
      // we try to incorporate the prop values into the remap. If values is undefined or unchanged we
      // fall back to the onchange, onupdate firing below as normal
      const remapped = this.reMapValues(reversed, values) 

      if (values === undefined || values === props.values) {
        next.onChange(remapped)
        next.onUpdate(remapped)
      }
    }
    // move this case to an else if. If the domain changed, we now allow that conditional branch to
    // do a hands on update of the value as opposed to allowing this one to do it. Value updating is
    // tied with the domain changing so do it at the same time now
    else if (!equal(values, props.values)) {
      this.setValues(values, reversed)
    }
  }
```

And then also in slider.js

```
  // allow this function to accept values from a parameter instead of always using state. sometimes
  // state is stale
  reMapValues(reversed, vals) { 
    const { values } = this.state
    return this.setValues((vals || values.map(d => d.val)), reversed)
  }
```

**Comment by sghall** [comment]
Hey,  right.  We're not handling this case where both change correctly.  I think I follow your logic for the fix.  Sounds correct.  You want to make a PR?
