### ISSUE TITLE
Crossing handles while using mode 1 and onUpdate creates push effect

### ISSUE THREAD

**Issue by CameronAckermanSEL** [sghall/react-compound-slider#30]
### Problem or feature description:
When a slider is configured to use mode 1, uses onUpdate for the change hook, and is controlled, crossing the handles creates a push effect.

https://codesandbox.io/s/kokrqqxwor

### Steps to reproduce (for problems):

1. Define a slider with more than one handle
2. Specify mode 1
3. Use onUpdate event hook
4. Use a controlled slider
5. Cross handles
6. Observe that both handles are pushed

### Versions (for problems):

React-Compound-Slider: 0.15.1

React: 16.x

Browser: Chrome

Operating System: Linux

**Comment by CameronAckermanSEL** [comment]
I think it has to do with the getUpdatedValues call in utils.js not taking into account the crossing of the handles properly in the sort

**Comment by sghall** [comment]
Yeah, not sure what you want me to say on this.  The onUpdate is there so you can display the values while dragging.  It doesn't make any sense to set the values using onUpdate.

**Comment by CameronAckermanSEL** [comment]
Thanks @sghall , you saying "user error" is enough for me :)
