### ISSUE TITLE
Feature: Ability to drag multiple handles at once while maintaining handle distance

### ISSUE THREAD

**Issue by CameronAckermanSEL** [sghall/react-compound-slider#32]
### Problem or feature description:

It would be nice for a user to be able to drag two handles at the same time and maintain the distance between them.

I envision this being achievable by clicking and dragging the track.

**Comment by sghall** [comment]
Right. Great idea.  It's not something I need personally but would look at a PR.   I think you could likely do this right now by just creating a "custom mode" but haven't tried it.  

There is a custom mode example at the bottom of the page here:
https://sghall.github.io/react-compound-slider/#/slider-demos/material-ui

If you pass in a function as the mode it gets called like this:
https://github.com/sghall/react-compound-slider/blob/2d46f71a155870e30322c84d3d35f608d0602941/src/Slider/Slider.js#L357

So the custom mode example restricts the max separation to 100:
```js
function customMode(curr, next) {
     const [{ val: val1 }, { val: val2 }] = next
     
      if (Math.abs(val1 - val2) > 100) {
          return curr
      }

      return next
}
```

**Comment by CameronAckermanSEL** [comment]
Hey cool, thanks so much for the suggestion. We'll give it a shot and get back to you on how it went :)
