### ISSUE TITLE
Bug?: Drag threshold for triggering a move event on the slider is off center

### ISSUE THREAD

**Issue by CameronAckermanSEL** [sghall/react-compound-slider#33]
### Problem or feature description:

When dragging the handle of a slider, the handle doesn't seem to change positions at the mid point between ticks. It looks like the point at which it moves the handle is about 50% off the actual midpoint

Reproducible here: https://codesandbox.io/s/5woq82rz6k (the button can be ignored here, not relevant)

http://recordit.co/UrOJcxpQWf

In a similar vein, the clicking of the track behaves in the same way too. Clicking slightly to the left or right of the true midpoint does not correctly calculate the nearest tick to use as the destination of the new handle - instead the "midpoint" is about 50% off the mark.

### Steps to reproduce (for problems):

1. Have a slider with a step
2. Drag the handle over to another tick
3. Observe the handle position change doesn't happen at the mid point.

### Versions (for problems):

React-Compound-Slider: 0.15.1

React: 16

Browser: Chrome

Operating System: Linux

**Comment by sghall** [comment]
Thanks for bringing this to my attention.  There was a little fudging going on there on the thresholds, but you couldn't see it unless you made a slider with just a few steps like you did.  Fixed in 0.16.1 that was just released.  If you see any other issues let me know.

**Comment by RobertPepkaSEL** [comment]
Thanks for solving it! :)

**Comment by CameronAckermanSEL** [comment]
Hi @sghall , wanted to let you know how much my team and I appreciate your responsiveness and assistance over the last couple of days. This library has been a pleasure to use and has helped us succeeed in a difficult area, and we're impressed with how well crafted your library is.

**Comment by sghall** [comment]
Awesome.  Thanks! Your feedback has been really helpful.  Let me know if anything else comes up.
