### ISSUE TITLE
String Values for Ticks

### ISSUE THREAD

**Issue by neilchaudhuri** [sghall/react-compound-slider#35]
### Problem or feature description:

This is a question. I have been trying to create a simple two-handle slider with string values rather than integers. I have tried creating something from a fork of the [example](https://codesandbox.io/s/plzyr7lmj) to represent a range of sizes. I would like the ticks to be "XS," "S," "M," "L," "XL." I presume I need a mapping of these string keys to numerical values (e.g. 0-4) so the slider can do some math, but I haven't been able to get this to work. Is this even possible?

### Versions (for problems):

React-Compound-Slider: 0.15.0

React: 16.4.10 (with TypeScript)

Browser: Chrome Version 69.0.3497.81 (Official Build) (64-bit)

Operating System: macOS High Sierra 10.13.6

**Comment by sghall** [comment]
Hey there. Sure. Something like this?
https://codesandbox.io/s/y08pv1ok7j

**Comment by neilchaudhuri** [comment]
Thanks for this. I thought it would be possible, but I made it more complicated than needed.
