### ISSUE TITLE
API change: `values` vs `defaultValues`

### ISSUE THREAD

**Issue by josepot** [sghall/react-compound-slider#4]
### Problem or feature description:

API change: `values` vs `defaultValues`

I'm working on a project where I need to be able to update a Slider with the values of a couple input components and vice-versa.

The problem with the fact that `Slider` is a stateful component is that once I've set the default values, the only way that I have to externally "update" it is to use the `key` property to force a `componentWillMount` while I provide the new values through `defalutValues`... Which is quite hacky and not great performance-wise.

I think that a slightly improved version of this API would be to have a `values` prop instead of a `defaultValues` prop. The idea would be that only when the property `values` changes the component gets updated with the "external" values. Meaning that the component would still be stateful, but if the user provides a new Array of values, then those new values would take preference over its internal state.

There is only one tricky situation: what would happen if the `domain`, `step` or `reversed` properties get updated?

It depends on whether the `values` property also gets updated:

- If the `values` prop hasn't changed: then the component will re-calculate the new values based on the new range and then it would call the `onUpdate` and `onChange` functions (same behaviour that we have now).

- If the `values` prop has also changed: then those values will take preference and there is no point on calling the `onUpdate` and `onChange` functions.

Another advantage of this approach is that it's easy to make it backwards compatible with the current version.

**Comment by sghall** [comment]
Right on.  Agreed. Just took a quick look at this, but I think this comes down to making it work as "controlled" component. I'll take a closer look at what you sent and update this ticket.  Should have some time in the next few days.

Note to self:  
I think the mui slider on the master branch works like this. Could check out their logic:
https://github.com/mui-org/material-ui/blob/master/src/Slider/Slider.js
