### ISSUE TITLE
Follow and add value on Slider

### ISSUE THREAD

**Issue by PeterMK85** [sghall/react-compound-slider#40]
### Problem or feature description:
OnHover I would like to see the value itself and on click I want to add the actual value to the values array.

Not found a clear description in he readme for this. (Probably I missed it) 

Thanks

### Versions (for problems):

React-Compound-Slider:

React:

Browser:

Operating System:

**Comment by sghall** [comment]
Hey there.  Hmmmm...interesting question.  I was messing around with this a bit. If it's a small number of discrete values you could do something like this.  

https://codesandbox.io/s/rwjn53mkmn

You wouldn't show the grey on the tick boxes obviously.  That's just there to show you what's going on.  Needs some work. 

Not sure if that's what you were looking for.

**Comment by PeterMK85** [comment]
Hey @sghall 

Thanks for the quick reply.

Yep its getting closer, but for my use case I have a large amount of values (for ex 500 or more), and a user should see each and every value on hover.
_(I just presume, but the `Ticks` approach won't be the best solution for me)_

So probably a `Rail` component on hover would be a better start for this no? _(with passing the actual mouse position value to the onMouseEnter function)_

WDYT?

**Comment by sghall** [comment]
I see.  I think one way to support this  is to give you access to a function that uses the scale that translates from the event location to the step.  You can see how it gets used here...

https://github.com/sghall/react-compound-slider/blob/2e34a25051e037f51c18740bab335ccb5abbf5f3/src/Slider/Slider.js#L275

You could pass down the scale and expose a function in the Tracks and Rail components that would allow you to get the step value by passing in the x or y value (depending on if it's vertical or not).  I wouldn't allow the user to actually get the scale itself.

One wrinkle here is I check the dimensions before using it in case the browser has resized.  So need to think about that.

https://github.com/sghall/react-compound-slider/blob/2e34a25051e037f51c18740bab335ccb5abbf5f3/src/Slider/Slider.js#L265

You interested in doing a PR on this?
