### ISSUE TITLE
Hard to grab narrow bar

### ISSUE THREAD

**Issue by RafeSacks** [sghall/react-compound-slider#41]
Hi,

Nice work! I just have a usability question:

### Problem or feature description:
I am sizing my bar (Rail/Track) based on the Material Design spec: https://material.io/design/components/sliders.html#spec

```
const trackHeight = 2;
const thumbHeight = 12;
```

However, this makes it tricky to click the bar. This is a low priority question as it still works and is usable. I just wanted to thicken up the "hot spot" for mouse interaction. I tried using `margin` styling but even though the style was applied (more space around the bar) the actual "hot spot" was the same. I tried height and margin on all components just to see if any are used but no luck.

Any ideas?

**Comment by sghall** [comment]
Hey there,  good question.  Probably do something like...
https://codesandbox.io/s/kor53j61r

This needs some work, but I think you'll get the idea.  Put two divs in the track component.  You could do the same on the handles.  Make sense?

**Comment by RafeSacks** [comment]
That works great! I just repeated the extra `div`/`Fragment` wrap on the
main `Slider`'s `Rail`. Thank you very much!

If helpful, please feel free to share this styling setup. I implemented the
material-ui withStyles() pattern and this matches the Material Design spec
for sliders including theming (I hope):

// Based on Material Design spec:
// https://material.io/design/components/sliders.html#spec
const trackHeight = 2;
const thumbHeight = 12;

// All slider component styles are set here.
const styles = theme => ({
rail: {
backgroundColor: theme.palette.grey[400],
width: "100%",
height: trackHeight,
position: "absolute",
cursor: "pointer"
},
railHotspot: {
// backgroundColor: "green", // for debugging
width: "100%",
height: thumbHeight, // Invisible hotspot same size as thumb
top: thumbHeight * -0.5,
position: "absolute",
cursor: "pointer"
},
track: {
backgroundColor: theme.palette.secondary.main,
height: trackHeight,
position: "absolute",
zIndex: 1,
cursor: "pointer"
},
trackHotspot: {
// backgroundColor: "grey", // for debugging
height: thumbHeight, // Invisible hotspot same size as thumb
top: thumbHeight * -0.5,
position: "absolute",
cursor: "pointer"
},
handle: {
backgroundColor: theme.palette.secondary.main,
marginLeft: thumbHeight * -0.5,
marginTop: thumbHeight * -0.5,
width: thumbHeight,
height: thumbHeight,
border: 0,
borderRadius: "50%", // circle
// boxShadow: "1px 1px 1px 1px rgba(0, 0, 0, 0.2)", // Fun option
whiteSpace: "nowrap", // For child display inline-block to work
position: "absolute",
zIndex: 2,
cursor: "pointer"
},
timeLabel: {
position: "absolute",
bottom: "1em",
left: "-1em",
noWrap: true,
display: "inline-block" // Makes the AM/PM not wrap to next line
}
});


I am using the slider as a time range so the domain is [0, 24] with 0.5
increments and then I use this function to display it nicely over the
handle (that is the `timeLabel` style above.

export function pretty24Hours(info) {
// Hour decimal to hours and minutes
let hour = parseInt(Number(info));
let min = Math.round((Number(info) - hour) * 60);

// Solve for 12 hour clock including am/pm
let part = hour > 12 ? "PM" : "AM";
hour = hour > 12 ? hour - 12 : hour;
min = String(min).padStart(2, "0");

return `${hour}:${min} ${part}`;
}


....just wanted to give something back. Thanks again!

__________________________________________
Rafe

**Comment by RafeSacks** [comment]
That works great! I just repeated the extra `div`/`Fragment` wrap on the
main `Slider`'s `Rail`. Thank you very much!

If helpful, please feel free to share this styling setup. I implemented the
`material-ui` `withStyles()` pattern and this matches the [Material Design slider spec](https://material.io/design/components/sliders.html#spec) including theming (I hope):

    // Based on Material Design spec:
    // https://material.io/design/components/sliders.html#spec
    const trackHeight = 2;
    const thumbHeight = 12;

    // All slider component styles are set here.
    const styles = theme => ({
      rail: {
        backgroundColor: theme.palette.grey[400],
        width: "100%",
        height: trackHeight,
        position: "absolute",
        cursor: "pointer"
      },
      railHotspot: {
        // backgroundColor: "green", // for debugging
        width: "100%",
        height: thumbHeight, // Invisible hotspot same size as thumb
        top: thumbHeight * -0.5,
        position: "absolute",
        cursor: "pointer"
      },
      track: {
        backgroundColor: theme.palette.secondary.main,
        height: trackHeight,
        position: "absolute",
        zIndex: 1,
        cursor: "pointer"
      },
      trackHotspot: {
        // backgroundColor: "grey", // for debugging
        height: thumbHeight, // Invisible hotspot same size as thumb
        top: thumbHeight * -0.5,
        position: "absolute",
        cursor: "pointer"
      },
      handle: {
        backgroundColor: theme.palette.secondary.main,
        marginLeft: thumbHeight * -0.5,
        marginTop: thumbHeight * -0.5,
        width: thumbHeight,
        height: thumbHeight,
        border: 0,
        borderRadius: "50%", // circle
        // boxShadow: "1px 1px 1px 1px rgba(0, 0, 0, 0.2)",
        whiteSpace: "nowrap", // for child display inline-block to work
        position: "absolute",
        zIndex: 2,
        cursor: "pointer"
      },
      timeLabel: {
        position: "absolute",
        bottom: "1em",
        left: "-1em",
        noWrap: true,
        display: "inline-block" // makes the AM/PM not wrap to next line
      }
    });

I am using the slider as a time range so the domain is [0, 24] with 0.5
increments and then I use this function to display it nicely over the
handle (that is the `timeLabel` style above.

    export function pretty24Hours(info) {
      // Hour decimal to hours and minutes
      let hour = parseInt(Number(info));
      let min = Math.round((Number(info) - hour) * 60);
    
      // Solve for 12 hour clock including am/pm
      let part = hour > 12 ? "PM" : "AM";
      hour = hour > 12 ? hour - 12 : hour;
      min = String(min).padStart(2, "0");
    
      return `${hour}:${min} ${part}`;
    }


....just wanted to give something back. Thanks again!

**Comment by sghall** [comment]
Awesome.  Yes!  Thanks for the styles!  I made a quick CodeSandbox so others can use them and linked to it from the readme:
https://codesandbox.io/s/k91omlr1wo

Really looks pretty good.  Thanks again.
