### ISSUE TITLE
Mouse events over <Track>

### ISSUE THREAD

**Issue by thunderkid** [sghall/react-compound-slider#49]
Many sliders, eg the ones on youtube or [https://plyr.io/](https://plyr.io/) provide a moving tooltip as you hover over the slider bar. I'm trying to reproduce this on `react-compound-slider`. But the `rcs` slider bar consists of (at least) two parts. The part to the right of the `Handle` is the `Rail` and I can capture its mouse events like this:
```
<Rail>
    {({ getRailProps }) => (
        <div onMouseEnter={this.mouseOverRail} onMouseMove={this.mouseOverRail} onMouseLeave={(e) => this.mouseOverRail(null)} className='rccrail' {...getRailProps()} />
    )}
</Rail>

```
But the part to the left of the rightmost `Handle` consist of some `<Track>`s, which are defined  differently. I can't see how to add mouse events to these and have them handled by the same component that handles the `mouseOverRail` events. 

Is there an example of how to do this? Thanks!

**Comment by sghall** [comment]
Someone else asked about something similar.  Seems like we could just expose a function in the components that you pass an event or just some coordinates  and get a value back...you can get an idea of what happens here...

https://github.com/sghall/react-compound-slider/blob/7b7d01a45326f406abd3d5d1089d8960acb01d7e/src/Slider/Slider.js#L275

Needs some thought but seems like you could mouseover any track rail etc and just call the function and get the value at that location.  Interested in working on this?

**Comment by thunderkid** [comment]
Sure, I'll take a look. 

What about the approach of creating `<Tooltip>` as an optional additional child component passed to `<Slider>`. It could take props `{value: number, percent: number, handleId: string | null, handleIsActive: boolean}` and in `render` set `style={{ left: '${percent}%' }}` just as `Handle` does. User could then change style depending on whether it's appearing as a track hover vs a handle drag.

This would cover the use cases I can think of, and would keep things consistent with the existing paradigm.

**Comment by sghall** [comment]
Having trouble seeing how this would work.  I like the idea, but I'm not sure how you would get the props for the tooltip.  You want to put together a PR and we'll take a look?

**Comment by sghall** [comment]
Let's fold this one into this tooltip discussion in https://github.com/sghall/react-compound-slider/issues/46
