### ISSUE TITLE
Alternating Track Display

### ISSUE THREAD

**Issue by wschmrdr** [sghall/react-compound-slider#54]
### New feature description:
When I am looking to adjust four (or any even number of) handles on my slider, I would think a common use case would be that the track displays would alternate.

In the case of 4 handles, the track between handles 1 and 2 would be "active" (i.e. use track color), the track between handles 3 and 4 would be "active", but the track between handles 2 and 3 would be "inactive" (i.e. use rail color), along with left and right being "inactive" as can presently be set.

Therefore, I am requesting, for a feature, the ability to alternate "active" tracks when the number of handles is even.

### Visual Example

This is what it looks like today:

![slider_request](https://user-images.githubusercontent.com/7564215/51615233-54cc3280-1ef5-11e9-897d-1da80d637d47.png)

This is what it would look like with the feature added:

![slider_request_2](https://user-images.githubusercontent.com/7564215/51615240-58f85000-1ef5-11e9-818e-3f3c928e8784.png)

**Comment by sghall** [comment]
Hey there.  Good question.

You can do that right now.  The `tracks` are just an array so you can manipulate it.  So for alternating you can just filter:

```
          <Tracks>
            {({ tracks, getTrackProps }) => (
              <div>
                {tracks
                  .filter((d, i) => i % 2 !== 0)
                  .map(({ id, source, target }) => (
                    <Track
                      key={id}
                      source={source}
                      target={target}
                      getTrackProps={getTrackProps}
                    />
                  ))}
              </div>
            )}
          </Tracks>
```

Here's a sandbox:
https://codesandbox.io/s/mzvmj0pvn9

**Comment by wschmrdr** [comment]
Very cool. Thanks much. :+1:

**Comment by wschmrdr** [comment]
I'll give this a close since the feature request is already available. :)
