### ISSUE TITLE
Not correct work on ipad

### ISSUE THREAD

**Issue by kodermax** [sghall/react-compound-slider#59]
### Problem or feature description:
Works worse than https://material-ui.com/lab/slider/
### Versions (for problems):

React-Compound-Slider: last

React: 16.8

Browser: Chrome

Operating System: IOS

**Comment by sghall** [comment]
This library does not render any content it just provides helpers to fire mouse and touch events at the appropriate times. 

The demos are just to help people get started but are not optimized for mobile.  The demos are also not tested on mobile devices other than my Android phone.  

If you're not comfortable writing your own components and testing them on mobile devices, this library is not a good choice for you.

**Comment by kodermax** [comment]
Why don't you want to make the slider work good on mobile devices?
