### ISSUE TITLE
Feature request: onSlideStart and onSlideEnd

### ISSUE THREAD

**Issue by bvandenbos** [sghall/react-compound-slider#6]
It would be convenient to expose events for beginning and ending a slide operation (from mouseDown/touchStart to mouseUp/touchEnd) from the `Slider` component.  This would give slider users more control over the user experience.

I believe one could stitch this together by passing around custom mouseDown/touchStart handlers to Handle and Rail components and inferring mouseUp from the `onChange` event (or binding it oneself on document), but it's a bit cumbersome.

If it makes sense to add this feature, I could maybe take a crack at a PR.

**Comment by sghall** [comment]
Hey.  Right on.  I think this is a feature that other people would want.  Seems like you could get the slide start here...

https://github.com/sghall/react-compound-slider/blob/master/src/Slider/Slider.js#L148

And the slide end here...
https://github.com/sghall/react-compound-slider/blob/master/src/Slider/Slider.js#L265
And here...
https://github.com/sghall/react-compound-slider/blob/master/src/Slider/Slider.js#L274

I don't think you would need to touch the other components, but maybe I don't understand how you want it to work.  Check it out and let me know if you want to do a PR.

**Comment by sghall** [comment]
Added this is the latest release!
