### ISSUE TITLE
how to show 1 track when there are no handles?

### ISSUE THREAD

**Issue by vanyakosmos** [sghall/react-compound-slider#66]
### Problem
> [Any slider has handles + 1](https://sghall.github.io/react-compound-slider/#/component-api/tracks)

but when slider has zero handles it doesn't render one track.

### Steps to reproduce:
`<Slider values={[]}>`
Use `Tracks` without parameters (with left and right enabled).

**Comment by vanyakosmos** [comment]
https://github.com/sghall/react-compound-slider/blob/0ecf225e3e1245b999b4a58380de34ec8c59e0ac/src/Tracks/Tracks.js#L33-L50
the problem is here I guess

`target` is not created because when number of handles is zero then after first (and only) run through the loop only `source` is created, that's why we need to get rid of `else` and let target to be created:

```
if (i === 0 && left) {
  source = { id: '$', value: domain[0], percent: 0 }
}
if (i === handles.length && right) {
  target = { id: '$', value: domain[1], percent: 100 }
}
```

**Comment by sghall** [comment]
Hmmm...I actually don't see this as a problem.  Why would you want to do this? If you click on the track what do you expect to happen?

**Comment by vanyakosmos** [comment]
In my slider I have clickable tracks and dynamic number of handles. And when all handles are gone then I still need to be able to add new ones + show track related info.

[here is demo with fixed track](https://i.imgur.com/OVNyZaj.mp4)

Also statement from docs "Any slider has handles + 1" then will be a lie (:

**Comment by sghall** [comment]
Ok.  Sure you can do that right now, you can render whatever you like when handles.length === 0.  Feel free.  You just have to be a good enough developer to see that :)
