### ISSUE TITLE
Rotate Slider

### ISSUE THREAD

**Issue by shubhamtaunk** [sghall/react-compound-slider#69]
Hi, I'm using this library to make a slider which is rotated by certain degrees.
![Screenshot 2019-03-12 at 3 24 21 PM](https://user-images.githubusercontent.com/23508423/54190996-0392f500-44db-11e9-9cd6-af38b3c8a76e.png)

I rotated the slider using CSS but after rotation, the drag on Handle and click on Slider is not working properly. And this behaviour intensifies as the angle of rotation is increased.
Is it possible to create rotated sliders using react-compound-slider?

**Comment by sghall** [comment]
Hi there. I think you could do this, but it would take some work.  I don't offer general support for this library.  It might be best to fork it or use another library.
