### ISSUE TITLE
Updating slider value programatically doesn't always re-render

### ISSUE THREAD

**Issue by rweller59** [sghall/react-compound-slider#72]
### Versions (for problems):

React-Compound-Slider:

React:

Browser:

Operating System:

**Comment by rweller59** [comment]
I am still struggling with this and hoping that you can take a quick look at the sample in codesandbox
https://codesandbox.io/s/7m9pk54rx1?fontsize=14

I am changing slider value 'normally' and through an external picker. When I change the value with the picker, the slider updates every other time. State is changing appropriately and re-rendering is executed every time. Changing slider with slider controls works as expected.

Steps to re-produce:
 - pick a date on the timedate picker, slider does not update
 - pick a date on the timedate picker, slider does update

**Comment by sghall** [comment]
You're sending values that are outside the domain.  They are getting coerced into the domain.  Add the "warnOnChanges" prop to see when values are being coerced.
