### ISSUE TITLE
StopPropagation supported?

### ISSUE THREAD

**Issue by JoeZman** [sghall/react-compound-slider#74]
Do you have a suggestion on a way to handle mouse down events on the rail and/or tracks?  In some cases, we would like to stop propagation and perform custom behavior.  We would like handles moved by clicking and dragging a handle, not a click on the rail or track.  Thanks!

**Comment by sghall** [comment]
Hey, there.  Not a 100% clear on what you want to do.  If you don't want events on the rail and tracks don't use `getRailProps` and `getTrackProps`

Just for anyone who may visit this.  This library use the [same pattern as downshift](https://github.com/downshift-js/downshift#customizing-handlers).

`getRailProps` just looks like this:

https://github.com/sghall/react-compound-slider/blob/d0a12f251dca91c4fa544987b53b37ce419b9655/src/Rail/Rail.js#L6
```js
  getRailProps = (props = {}) => {
    const { emitMouse, emitTouch } = this.props

    return {
      ...props,
      onMouseDown: callAll(props.onMouseDown, emitMouse),  // you could add your own mouse down, both get called
      onTouchStart: callAll(props.onTouchStart, emitTouch), // you could add your own touch start, both get called
    }
  }
```
If you don't need the events at all.  Just don't use `getRailProps`.

Same is true for tracks.

https://github.com/sghall/react-compound-slider/blob/d0a12f251dca91c4fa544987b53b37ce419b9655/src/Tracks/Tracks.js#L6

```js
  getTrackProps = (props = {}) => {
    const { emitMouse, emitTouch } = this.props

    return {
      ...props,
      onMouseDown: callAll(props.onMouseDown, emitMouse),
      onTouchStart: callAll(props.onTouchStart, emitTouch),
    }
  }
```

Does this answer the question?

**Comment by JoeZman** [comment]
Certainly does.  Thanks!
