### ISSUE TITLE
Focus on handle when rail is clicked.

### ISSUE THREAD

**Issue by s-taylor** [sghall/react-compound-slider#76]
### Feature description:

Enable the ability to click on a rail and apply focus to the handle automatically. If the slider has multiple handles, it would be nice if it could highlight the specific handle that moved.

If there is a way to do this already please let me know. 
I wasn't able to get this to work using onClick events on either the rail or a div wrapping the rail. 
I was able to get it to work by wrapping the entire slider in a div with an onClick, but this isn't the same functionality. I used `React.forwardRef` on the handle component to enable setting focus.

**Comment by sghall** [comment]
Hey, thanks for opening the issue.  It seems like this is related to https://github.com/sghall/react-compound-slider/issues/50.  If, when the user clicked on the rail or track, it made that closest handle active would that solve the issue?  The `activeHandleID` is passed to the children of the `Handles` component so you just compare it to the id of each of the handles and if it matches you make it focus.

You think this should be the default behavior?  So, as mentioned in that ticket, when somebody clicks on the rail or track the closest handle would move to that location and be made active.  If the user starts to drag without lifting up then they will move the handle (this is how YouTube works).  Right now, you click then have to release it and mouse down on the handle to make it active.

I think adding this logic would be easy to do, but it would be a breaking change unless we made it a prop to opt in.

**Comment by ArlindoTorres** [comment]
I also think it should be default behavior or have that option with a prop would be really useful.

**Comment by sghall** [comment]
Ok.  Thanks for the feedback.   I'll give this a shot in the next few days.

**Comment by s-taylor** [comment]
Thanks for your reply, sorry for some reason I didn't receive a notification you replied.

I think what you suggested makes complete sense and should be the default behaviour. When there are multiple handles, it is already is smart enough to determine which handle you are intending to move when you click on the rail, so I think it makes sense to focus on the handle that was moved.

I just had a look at how youtube works as a reference point. Interestingly youtube actually lets you focus on the rail itself? Which also supports the arrow keys. But that wouldn't work with multiple handles so I think focusing on the handle makes more sense.

**Comment by sghall** [comment]
Sorry for the delay.  I just released a beta version to address this.  @s-taylor and @ArlindoTorres could you guys try it out?   If I don't hear any issues I'll release it officially on Monday as Version 2.0.0.

Install the beta:
```
npm install react-compound-slider@beta
```
Should get you `react-compound-slider@2.0.0-beta.0` right now.  I tried it out in the demos and one test app I'm working on.  Seems to do the trick.

**Comment by ArlindoTorres** [comment]
I'm currently traveling but I will test it when I get back on Sunday. Thank you for the update as it will be very useful.

**Comment by sghall** [comment]
Released in 2.0.0!

**Comment by s-taylor** [comment]
Thanks so much for this, will try it out!

**Comment by s-taylor** [comment]
Thanks for this by the way. I have finally got around to implementing it.
For anyone wondering how to use this this, basically I pass down an `isFocused` prop to each handle which is `isFocused={activeHandleID === handle.id}`.

Then in the handle component, something like...
```
const handleRef = React.useRef(null);

React.useEffect(() => {
  if (handleRef && isFocused) handleRef.current.focus();
}, [handleRef, isFocused]);

return (
  <Handle ref={handleRef} />
);
```

There is one gotcha, which is that the `activeHandleId` seems to only appear temporarily, before reverting to `null`. I'm not sure whether that's intentional or not? But it's not really an issue because you only set focus when `isFocused` is true, you never unset focus.
