### ISSUE TITLE
Preventing touch events fails in Chrome 56 and higher

### ISSUE THREAD

**Issue by esseb** [sghall/react-compound-slider#79]
### Steps to reproduce (for problems):
1. Open https://sghall.github.io/react-compound-slider/#/simple-value-slider in Chrome
2. Open devtools
3. Toggle device toolbar in devtools and select e.g. `iPhone 5/SE`
 * This is to ensure touch events are emulated
4. Click and track the handle to move it
5. While moving the handle move the mouse up and down

During step 5 it is possible to move the entire page up and down while moving the handle. I assume `e.preventDefault()` is intended to prevent the touch event from scrolling the page?

The console tab in devtools gives this error: `[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080`

I assume https://github.com/sghall/react-compound-slider/blob/2e1cc2d3423af0e2387df599b29df41495756614/src/Slider/Slider.js#L234 is meant to prevent it being possible to scroll the page up and down while moving the handle.

Unfortunately this is a React bug: https://github.com/facebook/react/issues/8968

### Solution
I simply set the style `touch-action: none;` on my main slider element. This prevents the user from being able to scroll the page up and down while interacting with the slider on a touch device, and also gets rid of Chrome's console warning.

An alternative solution which would require code change in `react-compound-slider` is to add the touch event listeners manually, see https://github.com/facebook/react/issues/8968#issuecomment-279101852

I think the CSS solution is the best solution here and should probably be set as an inline style by `react-compound-slider`. I'm not sure if there are any drawbacks I'm not aware of.

### Versions (for problems):

React-Compound-Slider: 1.2.1

React: 16.8.0

Browser: Chrome v74.0.3729.108

Operating System: macOS Mojave v10.14.4

**Comment by sghall** [comment]
Hey, there.  Thanks for pointing out this issue and providing some background.  I just released a fix in version 1.2.2 a few minutes ago.  Since calling preventDefault on mobile was not actually doing anything other than causing a warning I just don't call it on mobile anymore.  The preventDefault was mainly helpful for the vertical sliders, so I added the `touch-action: none;` css on the vertical demos.   Thanks for that css tip!

If you could, try out 1.2.2 and let me know if there's any other issues.

**Comment by esseb** [comment]
1.2.2 works great, no console warnings when there is no `touch-action: none;` style. The demos look good too.

Closing this issue now, thanks for a great library :)
