### ISSUE TITLE
Allocation mode

### ISSUE THREAD

**Issue by Vincz** [sghall/react-compound-slider#80]
### Feature description:
Hey man! First of all, thank you for this really nice component.  

I have a special use case. I'm using it to allocate a percentage among items. So I have a value of 100% to share between x items. The sum of allocation is then always 100%. So, if I have values like `[0, 20, 30, 100]` it means that I have 3 items, the first one has 20%, the second one 10% and the last one 70%. So, in my use case, the first and the last handle should be disabled, so the first entry of values is always 0 and the last is always 100.
I removed the first and last handle, but it is not enough as it's always possible to click on the track to adjust the value of the first and last values index. And I didn't find anything to prevent a values change;

Would you accept a PR with this feature ? It could be either a new "mode" (mode 4), or a simply a feature of the mode 3. Like a prop `fixedEdges` or something. Also, I would need to be able to have the distance between two handle as a property (and not fixed on the `step` prop).

**Comment by sghall** [comment]
Thanks for opening the issue.  Hmmm...like you say, it seems like a special use case and probably not something that would be added to the library.  I'm trying to keep this library as lean as I possibly can. If you want to create a sandbox we could link to it or you could publish it on NPM.

**Comment by Vincz** [comment]
Ok man! I understand you point of view, event if I'm not sure this use case is so special (in my case, I did had this need a couple of times on different projects already). I added a PR, just in case, and for you to see that the size impact on gziped version is just 1% . But it's really up to you :) 
Let me know if you want to integrate it and if you want me to add doc and/or examples.

**Comment by sghall** [comment]
Awesome.  Thanks!
