### ISSUE TITLE
Demos not working on IE11

### ISSUE THREAD

**Issue by jesseko** [sghall/react-compound-slider#81]
### Problem or feature description:
Console is loggin as IE11 syntax error
May not be in actual component code, might be something else on the demo site (but it's discouraging to a person trying to verify IE11 compatability).

### Steps to reproduce (for problems):
visit https://sghall.github.io/react-compound-slider/#/slider-demos/horizontal on IE11

### Versions (for problems):

React-Compound-Slider: current

Just viewing demo site https://sghall.github.io/react-compound-slider/#/slider-demos/horizontal

Browser: IE11

Operating System: Win 8.1 via virtualbox on OSX host

**Comment by sghall** [comment]
Hey there.  Thanks for letting me know about this issue.  Sounds like it's the babel polyfill on the site.  I just added it.  Could you try it again?  I don't have a way to verify it on IE right now.

If it doesn't work, paste in a screenshot with the error.  The library should work on IE.

**Comment by jesseko** [comment]
Yep
still crashing :(
And in typical IE fashion the error is really opaque

![image](https://user-images.githubusercontent.com/153062/57545155-5687fd80-730e-11e9-91f7-6120d00b1910.png)

but when I click it it jumps here.  You can see the cursor near the right edge about half way down
![image](https://user-images.githubusercontent.com/153062/57545191-75868f80-730e-11e9-922f-8a202a74ad8f.png)

So yeah, looks like maybe a babel issue with that arrow function not getting transpiled?  Doesn't look like that part is even in your code...

**Comment by sghall** [comment]
Ok. Fixed.  Found a machine to try it out on.  Try loading it now.

**Comment by jesseko** [comment]
Verified!
IE11 looks great now, thanks!
