### ISSUE TITLE
Custom Mode

### ISSUE THREAD

**Issue by JoeZman** [sghall/react-compound-slider#82]
### Versions (for problems):

React-Compound-Slider:

React:

Browser:

Operating System:

**Comment by JoeZman** [comment]
Question...  Is it possible to limit the travel of a handle between a given range?  For example, with a domain of say 0...100, we would like to restrict the user between extents 20...80 (i.e., user would not be able to drag the handle beyond the 20...80 extents).  Is this the purpose of "custom mode" on the Slider?  And if so, do you happen to have a typescript example :-)  Thanks.

**Comment by sghall** [comment]
It would be a variant of:
https://github.com/sghall/react-compound-slider/issues/12#issuecomment-476351172
