### ISSUE TITLE
Typescript incorrect

### ISSUE THREAD

**Issue by tonyhallett** [sghall/react-compound-slider#86]
### Problem :
  Typescript incorrect
### Steps to reproduce (for problems):
  Use the current typescript
### Versions (for problems):
 
React-Compound-Slider:
  2.0.0
React:
  any
Browser:
  any
Operating System:
  any

export type SliderModeValue = {
  key: string;
  value: number;
}

The value property should be val ( as agrees with your mode2 and mode 3 function

**Comment by sghall** [comment]
Good point.  Thanks for pointing that out.  I'll get a fix out for that.

**Comment by sghall** [comment]
This was released in version 2.1.0.  Try it out and open this back up if there's any issues.
