### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by frandevel** [sghall/react-compound-slider#88]
### Problem or feature description:

Type definitions do not exist. It would be very handy if you need to use the component with Typescript.

### Steps to reproduce (for problems):

Try to use the component in a Typescript code base

### Versions (for problems):

any

React-Compound-Slider:

2.0

React:

16.8.3

Browser:

any

Operating System:

any

**Comment by sghall** [comment]
The types are there.  There's a number of people who use this slider with Typescript.  Not sure what else to say on this.  Can you provide any more info on your setup?  Look in node_modules/react-compound-slider.  The types are there right?

**Comment by frandevel** [comment]
You're completely right @sghall . Types were there. I went right ahead to searching the types in definetlytyped. I close the ticket and sorry for the inconveniences
