### ISSUE TITLE
Please export interface HandlesProps

### ISSUE THREAD

**Issue by tonyhallett** [sghall/react-compound-slider#89]
[interface HandlesProps](https://github.com/sghall/react-compound-slider/blob/cb877f0dc2597871458d5e648404b0e1cbd3ace5/src/Handles/Handles.d.ts#L18)

**Comment by sghall** [comment]
Thanks for opening the issue.   I don't use Typescript so the feedback is great. Exported those and a few other things I could quickly find.  Try it out in version `2.2.0` and open this back up if there's any issues.
