### ISSUE TITLE
Tutorial step one does not work as described

### ISSUE THREAD

**Issue by michelpmcdonald** [sghall/react-compound-slider#92]
### Problem or feature description:
Following the tutorial, step 1 results in an error "TypeError
Cannot read property 'name' of undefined"

### Steps to reproduce (for problems):
Follow tutorial exactly, my dev env did not catch it, but codesandbox.com did a pretty good job of finding the issue.  Kept thinking I did something wrong until I did the tutorial in codesandbox.com and saw the error

The issue is the comment in this line:
`<div` style={railStyle} /> // Add a rail as a child.  Later we'll make it interactive.

Perhaps change to:
`<div style={railStyle /* Add a rail as a child.  Later we'll make it interactive.*/ } />

**Comment by sghall** [comment]
Hi there.  I see.  Good point.  I will update that.

**Comment by sghall** [comment]
Thank you.  Took care of this.
