### ISSUE TITLE
Is there a way to be able to slide only to certain values?

### ISSUE THREAD

**Issue by karzyna** [sghall/react-compound-slider#95]
### Problem or feature description:
Hi, I'm wondering if there's a way to set up Slider to be only able to slide to where the ticks are located and not between them? I've tried to achieve this by setting steps dynamicaly based on values diff, but for some reason slider breaks when I try it.

Here's what I'm talking about
https://codesandbox.io/s/react-compound-slider-material-design-spec-w1b21?fontsize=14
Please at least tell me what I'm doing wrong

### Versions (for problems):
React-Compound-Slider: 2.3.0
React: 16.9
Browser: Chrome
Operating System: Win

**Comment by sghall** [comment]
Hey there.  Thanks for making the sandbox.  I think it would be a custom mode prop.  Here's a sketch of the basic idea:
https://codesandbox.io/s/react-compound-slider-material-design-spec-8p1kb

If the values are dynamic you'd have to make something much more sophisticated.  Hope that helps.

**Comment by karzyna** [comment]
Hi, yes I meant dynamic values. Maybe consider adding such feature in future, anyway thanks :)
