### ISSUE TITLE
'd3-array@^1.2.4' is not in the npm registry

### ISSUE THREAD

**Issue by ronnymeli** [sghall/react-compound-slider#96]
### Problem or feature description:
D3 Array dependency is missing 
Not Found - GET https://registry.npmjs.org/d3-array/-/d3-array-1.3.0.tgz
'd3-array@^1.2.4' is not in the npm registry.

### Steps to reproduce (for problems):
npm install react-compound-slider

### Versions (for problems):
Latest

![image](https://user-images.githubusercontent.com/31705830/65455228-2e142200-de1d-11e9-87c7-e5c1c66d99e6.png)

**Comment by sghall** [comment]
Hola.  Interesante.  Me parece que se esta pidiendo version 1.3.0 y no 1.2.4 (?)  Para mi, se pide version 1.2.4 cuando instalo locally. No hay errores.

Anybody else see this?  Not sure why it wouldn't resolve correctly. It's asking for 1.3.0.  Can you let me know if this persists?  I assume you have tried to install it multiple times.

**Comment by sghall** [comment]
Hopefully, this has cleared up.

**Comment by adrianescat** [comment]
Using node `v8.10.0` I have the same problem:

`Not Found - GET https://registry.npmjs.org/d3-array/-/d3-array-1.3.0.tgz`

<img width="775" alt="Screen Shot 2019-10-21 at 15 35 17" src="https://user-images.githubusercontent.com/7191028/67232776-69a00d00-f418-11e9-8df6-3e7b3498116f.png">
