### ISSUE TITLE
Can we develop non linear slider with react component slider?

### ISSUE THREAD

**Issue by Sibgha228** [sghall/react-compound-slider#97]
Nouislider has option to define a nonlinear slider. Do we have a possibility to do with react compound slider?  

Here is a link:
https://refreshless.com/nouislider/examples/#section-non-linear.

**Comment by sghall** [comment]
Hey there.  Sure, you control what gets rendered so you can translate the values from one scale to another.  I don't have any examples. 

See https://github.com/sghall/react-compound-slider/issues/27
